# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pvtr < Formula
  desc "A pluggable compliance testing framework"
  homepage "https://github.com/privateerproj/privateer"
  version "0.16.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/privateerproj/privateer/releases/download/v0.16.0/privateer_Darwin_all.tar.gz"
    sha256 "69a60ccc94a7ac74197f67f435dcfe15b74f80f74615727a6c82f61a20b05101"

    define_method(:install) do
      bin.install "pvtr"
      bin.install_symlink "pvtr" => "privateer"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/privateerproj/privateer/releases/download/v0.16.0/privateer_Linux_x86_64.tar.gz"
      sha256 "0818c314f0d63036d26bc6797b958c46f99e2f8da8a891d214a904c82ca2b0b4"
      define_method(:install) do
        bin.install "pvtr"
        bin.install_symlink "pvtr" => "privateer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/privateerproj/privateer/releases/download/v0.16.0/privateer_Linux_arm64.tar.gz"
      sha256 "df7dd5a2f2fdaf0d4af34e00647e3266850f0147615603d9ca9dcb63638aa393"
      define_method(:install) do
        bin.install "pvtr"
        bin.install_symlink "pvtr" => "privateer"
      end
    end
  end

  test do
    system "#{bin}/pvtr", "version"
  end
end
