issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:privateerproj/(privateer|pvtr):(pull_request|ref:refs/heads/main|ref:refs/tags/v.*)
claim_pattern:
  job_workflow_ref: privateerproj/(privateer|pvtr)/.github/workflows/release.yaml@refs/heads/main

permissions:
  contents: write
