issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:privateerproj@116728460/pvtr@557844592:(pull_request|ref:refs/heads/main|ref:refs/tags/v.*)
claim_pattern:
  job_workflow_ref: privateerproj/pvtr/.github/workflows/release.yaml@refs/heads/main

permissions:
  contents: write
