issuer: https://token.actions.githubusercontent.com
subject: repo:privateerproj/privateer:ref:refs/heads/main
subject_pattern: repo:privateerproj/privateer:ref:refs/tags/v.*
claim_pattern:
  job_workflow_ref: privateerproj/privateer/.github/workflows/release.yaml@refs/heads/main

permissions:
  contents: write
